import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import products from '../products.json'
import { initiateCheckout } from '../lib/payments'

export default function Home() {
  console.log(
    'NEXT_PUBLIC_STRIPE_API_KEY',
    process.env.NEXT_PUBLIC_STRIPE_API_KEY
  )
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>SpaceJelly Shop</h1>

        <p className={styles.description}>
          Get started by editing
          <code className={styles.code}>pages/index.js</code>
        </p>

        <ul className={styles.grid}>
          {products.map(({ title, image, price, description, id }) => (
            <li className={styles.card} key={id}>
              <a href='#'>
                <img src={image} />
                <h2>{title}</h2>
                <p>${price}</p>
                <p>{description}</p>
              </a>
              <p>
                <button
                  className={styles.button}
                  onClick={() => {
                    initiateCheckout({
                      lineItems: [
                        {
                          price: id,
                          quantity: 1
                        }
                      ]
                    })
                  }}
                >
                  Buy now
                </button>
              </p>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
